package software.aoc.test.day07.a;

import org.junit.Test;
import software.aoc.day07.TachyonsTreeBuilder;
import software.aoc.day07.TachyonsTreeManager;

import static org.assertj.core.api.Assertions.assertThat;

public class TachyonsTest {

    private final String treeStructure = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;


    @Test
    public void small_structure_should_be_easy(){
        TachyonsTreeManager tachyonTree = TachyonsTreeBuilder.create().with(".......S.......\n...............").build();
        assertThat(tachyonTree.countTachyonsA()).isEqualTo(1);
    }

    @Test
    public void basic_aoc_test_should_be_fine(){
        TachyonsTreeManager tachyonTree = TachyonsTreeBuilder.create().with(treeStructure).build();
        assertThat(tachyonTree.countTachyonsA()).isEqualTo(21);
    }


}
