package software.aoc.test.day07.a;

import org.junit.Test;
import software.aoc.day07.a.TachyonTree;

import static org.assertj.core.api.Assertions.assertThat;

public class TachyonsTest {

    private final String treeStructure = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;


    @Test
    public void small_structure_should_be_easy(){
        TachyonTree tachyonTree = TachyonTree.create();
        assertThat(tachyonTree.with(".......S.......\n...............").countTachyons()).isEqualTo(1);
    }

    @Test
    public void basic_aoc_test_should_be_fine(){
        TachyonTree tachyonTree = TachyonTree.create();
        assertThat(tachyonTree.with(treeStructure).countTachyons()).isEqualTo(21);
    }


}
